name: "Android Commit"

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - '.github/'
      - 'app/'
      - 'assets/'
      - 'components/'
      - 'constants/'
      - 'app.json'
      - 'babel.config.js'
      - 'metro.config.js'
      - 'package-lock.json'
      - 'package.json'
      - 'tsconfig.json'

permissions:
  checks: write

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  unit_tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4

#      - name: "Install Node"
#        uses: actions/setup-node@v4
#        with:
#          node-version: 16
#          cache: "npm"
#
#      - name: "Restore Node Modules"
#        id: cache-npm
#        uses: actions/cache/restore@v3
#        with:
#          path: node_modules
#          key: v1-${{ runner.os }}-node-modules-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}

      - name: "Run Unit Tests via NPM"
        run: npm run test

      - name: "Publish Test Report"
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'build/reports/jest-junit/junit.xml'

#      - name: "Save Node Modules"
#        uses: actions/cache/save@v3
#        if: steps.cache-npm.outputs.cache-hit != 'true'
#        with:
#          path: node_modules
#          key: v1-${{ runner.os }}-node-modules-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
